# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: ollama:gemma3:4b
clients:
- type: openai-compatible
  name: ollama
  api_base: http://localhost:11434/v1
  api_key: ollama
  models:
  - name: gemma3:4b
  - name: phi4-mini:3.8b
  - name: qwen2.5-coder:3b
  - name: qwen2.5:3b
  - name: snowflake-arctic-embed2:568m
    type: embedding
    default_chunk_size: 1000
    max_batch_size: 100
