# vim:fileencoding=utf-8:foldmethod=marker

# BEGIN_KITTY_THEME
# Catppuccin-Mocha
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="Maple Mono NR NFMono CN"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# 透明背景
background_opacity 0.85
# 终端响铃
enable_audio_bell yes
# 最大历史记录
scrollback_lines 10240
