# Config file for sdboot-manage

# Kernel options to be appended to the "options" line
LINUX_OPTIONS="\
rd.luks.name=07fd74b4-40e9-4b6e-a511-9a8643938b21=gentoo \
rd.luks.name=67d50514-70c9-498e-9c9f-9c1a8742f2a3=lfs \
rd.luks.name=bf0c0524-cb1f-4d7d-b16f-3e6f4d228d0e=data \
rd.luks.name=b2119d08-484f-4d49-a37e-d2c459b7ee18=swap \
lsm=landlock,lockdown,yama,integrity,apparmor,bpf crashkernel=512M \
resume=UUID=2b407c83-dc1e-480e-a69d-2c3aba00dd69 hibernate.compressor=lz4 \
intel_iommu=on iommu=pt i915.enable_guc=3 zswap.enabled=0 \
splash plymouth.use-simpledrm nowatchdog quiet \
loglevel=3 systemd.show_status=auto rd.udev.log_level=3 \
vt.default_red=30,243,166,249,137,245,148,186,88,243,166,249,137,245,148,166 \
vt.default_grn=30,139,227,226,180,194,226,194,91,139,227,226,180,194,226,173 \
vt.default_blu=46,168,161,175,250,231,213,222,112,168,161,175,250,231,213,200"
#LINUX_FALLBACK_OPTIONS=""

# When DISABLE_FALLBACK is set to "yes", it will stop creating fallback entries for each kernel.
#DISABLE_FALLBACK="no"

# Use this pattern to match kernels which should be considered native OS kernels
#KERNEL_PATTERN="vmlinuz-"

# Setting REMOVE_EXISTING to "yes" will remove all your existing systemd-boot entries before building new entries
REMOVE_EXISTING="no"

# Unless OVERWRITE_EXISTING is set to "yes" existing entries for currently installed kernels will not be touched
# this setting has no meaning if REMOVE_EXISTING is set to "yes"
OVERWRITE_EXISTING="yes"

# When REMOVE_OBSOLETE is set to "yes" entries for kernels no longer available on the system will be removed
REMOVE_OBSOLETE="yes"

# If PRESERVE_FOREIGN is set to "yes", do not delete entries starting with $ENTRY_ROOT
#PRESERVE_FOREIGN="no"

# Setting NO_AUTOUPDATE to "yes" will stop the updates to systemd-boot when systemd is updated - not recommended unless you are seperately updating systemd-boot
#NO_AUTOUPDATE="no"

# Setting NO_AUTOGEN to "yes" will stop the automatic creation of entries when kernels are installed or updated
#NO_AUTOGEN="no"

# Use this to change the default initramfs prefix (e.g. when using booster)
#INITRD_PREFIX="initramfs"

# Additional entities to initrd can be added here, such as microcode if your initramfs does not include it.
#INITRD_ENTRIES=()
