# == Color ==
# This has various color options. (Will be expanded in the future.)
color:
  when: always
  theme: custom
# == Icons ==
icons:
  when: always
  theme: fancy
  separator: " "
# == Sorting ==
sorting:
  column: name
  reverse: false
  dir-grouping: first
