general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 3600
    on-timeout = notify-send "你已经超过 1h 未进行任何操作了！" && brightnessctl -s set 50%
    on-resume = notify-send "欢迎回来！" && brightnessctl -r
}

listener {
    timeout = 5400
    on-timeout = loginctl lock-session
    on-resume = notify-send "欢迎回来！" && brightnessctl -r
}

listener {
    timeout = 7200
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}
