export HISTSIZE=10240
export HISTFILE="${XDG_CACHE_HOME:-${HOME}/.cache}/zinit/history"
export SAVEHIST="${HISTSIZE}"
export HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups
