[source.crates-io]
replace-with = 'ustc'

[source.ustc]
registry = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[registries.ustc]
index = "sparse+https://mirrors.ustc.edu.cn/crates.io-index/"

[target.x86_64-unknown-linux-gnu]
linker = "/usr/bin/gcc"

[target.riscv64gc-unknown-linux-gnu]
linker = "/usr/bin/riscv64-linux-gnu-gcc"

[target.aarch64-unknown-linux-gnu]
linker = "/usr/bin/aarch64-linux-gnu-gcc"

[target.x86_64-unknown-linux-musl]
linker = "/usr/bin/musl-gcc"

[target.riscv64gc-unknown-linux-musl]
linker = "/usr/bin/riscv64-linux-musl-gcc"

[target.aarch64-unknown-linux-musl]
linker = "/usr/bin/aarch64-linux-musl-gcc"

[target.x86_64-pc-windows-gnu]
linker = "/usr/bin/x86_64-w64-mingw32-gcc"
