# 将所有变量同步到 systemd, 这个最先执行
exec-once = dbus-update-activation-environment --systemd --all

# 密钥链 & Polkit 代理 & Bitwarden
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = systemctl --user start hyprpolkitagent
exec-once = bitwarden-desktop --enable-wayland-ime

# 壁纸 & 夜间模式
exec-once = hyprpaper & hyprsunset

# 自动锁屏
exec-once = hypridle

# 自动加载插件
exec-once = hyprpm reload

# 状态栏 & 网络管理
exec-once = waybar & nm-applet

# 通知守护进程
exec-once = swaync

# KDE Connect
exec-once = kdeconnectd

# 剪贴板
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# 更新检查
exec-once = arch-update --tray

# 音效
exec-once = easyeffects --hide-window --service-mode

# 输入法
exec-once = fcitx5
