## 将 $HOME/.local/bin 加入 $PATH
env = PATH,$HOME/.local/bin:$PATH

## 个人信息
# env = USER,carlson
env = EMAIL,aubreycarlson24@outlook.com
env = HOSTNAME,Carlson-Laptop
env = LANG,zh_CN.UTF-8

## 优先使用集显渲染桌面
env = AQ_DRM_DEVICES,/dev/dri/intel-igpu:/dev/dri/nvidia-dgpu

## 光标主题
env = XCURSOR_SIZE,20
env = HYPRCURSOR_THEME,Bibata-Modern-Ice
env = HYPRCURSOR_SIZE,20

## QT6 应用主题
env = QT_QPA_PLATFORMTHEME,hyprqt6engine

## 显式声明桌面环境
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

## XDG 目录
env = XDG_CACHE_HOME,$HOME/.cache
env = XDG_CONFIG_HOME,$HOME/.config
env = XDG_DATA_HOME,$HOME/.local/share
env = XDG_STATE_HOME,$HOME/.local/state

## 强制这些应用使用 Wayland
env = ELECTRON_OZONE_PLATFORM_HINT,wayland
env = GDK_BACKEND,wayland,x11,*
env = PROTON_ENABLE_WAYLAND,1
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland

## 编辑器
env = EDITOR,helix
env = VISUAL,helix
env = SUDO_EDITOR,helix

## LFS & Gentoo
env = LFS,/mnt/lfs
env = GENTOO,/mnt/gentoo

## 规范应用数据路径
# Go
env = GOPATH,$XDG_DATA_HOME/go
env = GOMODCACHE,$XDG_CACHE_HOME/go/mod
# Rust & Cargo
env = CARGO_HOME,$XDG_DATA_HOME/cargo
env = RUSTUP_HOME,$XDG_DATA_HOME/rustup
# WakaTime
env = WAKATIME_HOME,$XDG_CONFIG_HOME/wakatime
# Visual Studio Code
env = VSCODE_PORTABLE,$XDG_DATA_HOME/vscode
env = VSCODE_CLI_DATA_DIR,$XDG_DATA_HOME/vscode/cli
# GTK 2.0
env = GTK2_RC_FILES,$XDG_CONFIG_HOME/gtk-2.0/settings.ini
# Gradle
env = GRADLE_USER_HOME,$XDG_DATA_HOME/gradle
# Maven
env = MAVEN_OPTS,-Dmaven.repo.local=$XDG_DATA_HOME/maven/repository
# Npm
env = NPM_CONFIG_USERCONFIG,$XDG_CONFIG_HOME/npm/npmrc
# NVIDIA CUDA
env = CUDA_CACHE_PATH,$XDG_CACHE_HOME/nvidia-cuda
# Ruby
env = BUNDLE_USER_CACHE,$XDG_CACHE_HOME/bundle
env = BUNDLE_USER_CONFIG,$XDG_CONFIG_HOME/bundle/config
env = BUNDLE_USER_PLUGIN,$XDG_DATA_HOME/bundle
# TeX Live
env = TEXMFHOME,$XDG_DATA_HOME/texmf
env = TEXMFVAR,$XDG_CACHE_HOME/texlive/texmf-var
env = TEXMFCONFIG,$XDG_CONFIG_HOME/texlive/texmf-config
# Wget
env = WGETRC,$XDG_CONFIG_HOME/wgetrc
# Wine
env = WINEPREFIX,$XDG_DATA_HOME/wineprefixes/default
# FVM
env = FVM_CACHE_PATH,$XDG_CACHE_HOME/fvm
env = FVM_GIT_CACHE_PATH,$XDG_CACHE_HOME/fvm-git

## QQ 固定 MAC 来支持记住账号
env = QQ_FIX_MAC,1

## 禁用 CUDA 运行时优化
env = CUDA_DISABLE_PERF_BOOST,1

## 光线追踪
env = VKD3D_CONFIG,dxr11,dxr
env = PROTON_ENABLE_NVAPI,1
env = PROTON_ENABLE_NGX_UPDATER,1
