# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = float-file-choice
    match:class = xdg-desktop-portal-gtk
    float = yes
    center = on
    size = 800 450
}

windowrule {
    name = float-qq-misc
    match:class = QQ
    match:title = [^QQ].*$
    float = yes
}

windowrule {
    name = kdeconnect-daemon
    match:class = org.kde.kdeconnect.daemon
    float = yes
    no_initial_focus = on
}
